### ISSUE TITLE
feature request: visual disabled state

### ISSUE THREAD

**Issue by gcottrell1** [ef-carbon/react-native-async-button#10]
I think that if the button is disabled there should be some visual cue, this could be as simple as applying an opacity to the idle component or allowing a `DisabledComponent` prop.

Thoughts?

**Comment by mattyclarkson** [comment]
`DisabledComponent` makes sense. Also we could pass `disabled` as an argument to the other components callback function. The `react-render-component` has had some upgrades and can now specify arguments that the callback can accept. `IdleComponent<boolean>` would mean we could pass a `disabled` state to `renderComponent`
